/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.interfaz.ABM;

import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import modelo.CONTROLADOR_M;
import vista.CONTROLADOR_V;
import vista.recursos.Formato;
import vista.recursos.ModeloTabla;
import vista.recursos.Validacion;

/**
 *
 * @author vicente
 */
public class AltaStock extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new ModeloTabla();
    private JTable tabla = new JTable();

    /**
     * Creates new form AltaStock
     */
    public AltaStock() {
        initComponents();
        this.tabla.getTableHeader().setReorderingAllowed(false);
        this.tabla.getTableHeader().setResizingAllowed(false);
        this.iniciarTabla();
        this.setearFecha();
    }

    public DefaultTableModel getModelo() {
        return modelo;
    }

    public JTextField getTxtTotal() {
        return txtTotal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numFact = new javax.swing.JLabel();
        txtNumFac = new javax.swing.JTextField();
        etqFecha = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane(tabla);
        txtTotal = new javax.swing.JTextField();
        etqTotal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCerrar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnAltaProd = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtFecha = new com.toedter.calendar.JDateChooser();

        setTitle("Alta de Stock");

        numFact.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        numFact.setText("Num. Factura:");

        txtNumFac.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        etqFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        etqFecha.setText("Fecha:");

        scrollPane.setAutoscrolls(true);

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTotal.setEnabled(false);

        etqTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etqTotal.setText("TOTAL:");

        btnCerrar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/Cancel.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.setToolTipText("Cerrar");
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/OK.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setToolTipText("Aceptar");
        btnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAceptar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/View.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("Buscar Producto");
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAltaProd.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnAltaProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/add product 25x25.png"))); // NOI18N
        btnAltaProd.setText("Agregar");
        btnAltaProd.setToolTipText("Alta de Producto");
        btnAltaProd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAltaProd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAltaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaProdActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/delete product 24x24.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("Eliminar Producto cargado");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(numFact)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumFac, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 378, Short.MAX_VALUE)
                        .addComponent(etqFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(etqTotal)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAltaProd)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerrar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numFact)
                        .addComponent(txtNumFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etqFecha))
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etqTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnAceptar)
                    .addComponent(btnBuscar)
                    .addComponent(btnAltaProd)
                    .addComponent(btnEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaProdActionPerformed
        CONTROLADOR_V.iniciaAltaProducto();
    }//GEN-LAST:event_btnAltaProdActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        int op = JOptionPane.showConfirmDialog(this, "¿Desea salir?");
        if (op == JOptionPane.YES_OPTION) {
            //CONTROLADOR_V.cerrarDB();
            this.dispose();
        }
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        CONTROLADOR_V.iniciaBuscarProducto();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        this.confirmar();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            Integer cup = (Integer) this.modelo.getValueAt(this.tabla.getSelectedRow(), 0);
            Integer fila = this.tabla.getSelectedRow();
            int op = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el producto de codigo: " + cup + "?", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            if (op == JOptionPane.YES_OPTION) {
                CONTROLADOR_V.eliminar(cup, fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Selecciones un Producto.", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void iniciarTabla() {
        this.modelo.addColumn("CUP");
        this.modelo.addColumn("Descripcion");
        this.modelo.addColumn("Stock Actual");
        this.modelo.addColumn("Stock Ingresante");
        this.modelo.addColumn("Costo Total de Comp");
        this.tabla.setModel(this.modelo);
        TableColumn codigo = tabla.getColumn("CUP");
        codigo.setMaxWidth(100);
        codigo.setMinWidth(100);
        TableColumn descripcion = tabla.getColumn("Descripcion");
        descripcion.setMaxWidth(468);
        descripcion.setMinWidth(468);
        TableColumn stockA = tabla.getColumn("Stock Actual");
        stockA.setMaxWidth(120);
        stockA.setMinWidth(120);
        TableColumn stockI = tabla.getColumn("Stock Ingresante");
        stockI.setMaxWidth(120);
        stockI.setMinWidth(120);
        TableColumn costoTo = tabla.getColumn("Costo Total de Comp");
        costoTo.setMaxWidth(150);
        costoTo.setMinWidth(150);
    }

    public void setearModelo() {
        this.tabla.setModel(modelo);
    }

    private void confirmar() {
        if (this.tabla.getRowCount() != 0) {
            if (!this.txtNumFac.getText().equals("") && Validacion.validarNumero(this.txtNumFac.getText())) {
                int op = JOptionPane.showConfirmDialog(this, "¿Desea guardar la factura compra con numero: " + this.txtNumFac.getText() + " con fecha de " + Formato.getFechaActual(txtFecha.getDate()) + "?", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                if (op == JOptionPane.YES_OPTION) {
                    if (CONTROLADOR_V.ingresaDatosFac(Integer.parseInt(this.txtNumFac.getText()), this.txtFecha.getDate())) {
                        JOptionPane.showMessageDialog(this, "Se guardo la Factura Compra con numero: " + this.txtNumFac.getText(), "Informacion", JOptionPane.INFORMATION_MESSAGE);
                        CONTROLADOR_V.mensaje("Se guardo la Factura Compra con numero: " + this.txtNumFac.getText());
                        this.limpiar();
                    } else {
                        JOptionPane.showMessageDialog(this, "ERROR");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese un numero de factura por favor.", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                this.txtNumFac.requestFocus();
                this.txtNumFac.selectAll();
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se cargo ningun Producto", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void setearFecha() {
        this.txtFecha.setDate(new Date());
        this.txtFecha.setDateFormatString("dd/MM/yyyy");
    }

    private void limpiar() {
        CONTROLADOR_M.iniciaAltaStock();
        this.modelo = new ModeloTabla();
        this.txtNumFac.setText("");
        this.txtTotal.setText("");
        this.iniciarTabla();
        this.setearFecha();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAltaProd;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel etqFecha;
    private javax.swing.JLabel etqTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel numFact;
    private javax.swing.JScrollPane scrollPane;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtNumFac;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
