/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.interfaz.ABM;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import vista.CONTROLADOR_V;
import vista.recursos.ModeloTabla;

/**
 *
 * @author vicente
 */
public class EliminarRubro extends javax.swing.JDialog {

    private boolean bandera;
    private JTable tabla = new JTable();
    private ModeloTabla modelo;

    /**
     * Creates new form EliminarRubro
     */
    public EliminarRubro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        CONTROLADOR_V.recupNombresRubros(this.listaRubr);
        txtCodigo.setText("");
        cargarTabla();
        jScrollPane1.setViewportView(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etqRubr = new javax.swing.JLabel();
        listaRubr = new javax.swing.JComboBox();
        etqCodigo = new javax.swing.JLabel();
        etqList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane(tabla);
        jSeparator1 = new javax.swing.JSeparator();
        btnCerrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JLabel();

        setTitle("Eliminar Rubro");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        etqRubr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etqRubr.setText("Seleccione Rubro:");

        listaRubr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        listaRubr.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Seleccione un Rubro"}));
        listaRubr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaRubrActionPerformed(evt);
            }
        });

        etqCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etqCodigo.setText("Codigo:");

        etqList.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        etqList.setText("Productos a eliminar:");

        btnCerrar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/Cancel.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.setToolTipText("Cerrar");
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/delete product 24x24.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("Eliminar");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        btnEliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEliminarKeyPressed(evt);
            }
        });

        txtCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCodigo.setText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etqList)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etqRubr)
                            .addComponent(etqCodigo))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigo)
                            .addComponent(listaRubr, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etqRubr)
                    .addComponent(listaRubr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etqCodigo)
                    .addComponent(txtCodigo))
                .addGap(18, 18, 18)
                .addComponent(etqList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnEliminar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void listaRubrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaRubrActionPerformed
        Integer id = CONTROLADOR_V.getContro_m().idRubro((String) listaRubr.getSelectedItem());
        if (id != null) {
            txtCodigo.setText(String.valueOf(id));
            cargarTabla();
        } else {
            txtCodigo.setText("");
        }
    }//GEN-LAST:event_listaRubrActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        formWindowClosing(null);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnEliminarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEliminarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            eliminar();
        }
    }//GEN-LAST:event_btnEliminarKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int op = JOptionPane.showConfirmDialog(this, "¿Desea cerrar la ventana de Eliminar?.\n"
                + "Perdera los datos cargados", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        if (op == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void eliminar() {
        if (!listaRubr.getSelectedItem().equals("Seleccione un Rubro")) {
            bandera = CONTROLADOR_V.getContro_m().eliminarRubro(Integer.parseInt(this.txtCodigo.getText()));
            if (bandera == true) {
                cargarTabla();
                JOptionPane.showMessageDialog(this, "Rubro: " + (String) listaRubr.getSelectedItem() + " eliminado", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                CONTROLADOR_V.mensaje("Rubro: " + (String) listaRubr.getSelectedItem() + " eliminado");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "Rubro: " + (String) listaRubr.getSelectedItem() + " no se pudo eliminar", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                CONTROLADOR_V.mensaje("Rubro: " + (String) listaRubr.getSelectedItem() + " no se pudo eliminar");
                limpiar();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor seleccione un Rubro.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiar() {
        listaRubr.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Seleccione un Rubro"}));
        CONTROLADOR_V.recupNombresRubros(this.listaRubr);
        this.txtCodigo.setText("");
    }

    private void cargarTabla() {
        tabla.setModel(modelo = new ModeloTabla());
        modelo.addColumn("Codigo");
        modelo.addColumn("Descripcion");
        if (!listaRubr.getSelectedItem().equals("Seleccione un Rubro")) {
            String nombre = (String) listaRubr.getSelectedItem();
            modelo = CONTROLADOR_V.getContro_m().recuperarDatos(nombre, modelo, "rubro");
        }
        TableColumn codigo = tabla.getColumn("Codigo");
        codigo.setMaxWidth(70);
        codigo.setMinWidth(70);
        TableColumn descripcion = tabla.getColumn("Descripcion");
        descripcion.setMaxWidth(568);
        descripcion.setMinWidth(568);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel etqCodigo;
    private javax.swing.JLabel etqList;
    private javax.swing.JLabel etqRubr;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox listaRubr;
    private javax.swing.JLabel txtCodigo;
    // End of variables declaration//GEN-END:variables
}
