/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.interfaz.ABM;

//import controlador.controlador_S_MGS.CONTROLADOR_S_MGS;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import modelo.dominio.PRODUCTO;
import vista.CONTROLADOR_V;
import vista.recursos.Validacion;
//import vista.Validacion;

/**
 *
 * @author vicente
 */
public class ModificarProducto extends JDialog {

    private boolean estado;
    private PRODUCTO mProducto;

    /**
     * Creates new form ModificarProducto
     */
    public ModificarProducto(Frame parent, boolean modal, PRODUCTO producto) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.mProducto = producto;
        this.txtCUP.setText(String.valueOf(mProducto.getCUP()));
        this.txtRubro.setText(mProducto.getnRubro());
        this.txtMarca.setText(mProducto.getnMarca());
        this.txtDesc.setText(mProducto.getDescripcion());
        this.txtCapVol.setText(String.valueOf(mProducto.getCap_vol_long()));
        this.txtUnidad.setText(mProducto.getnUnidad());
        this.txtPrecUni.setText(String.valueOf(mProducto.getPrecio_Unitario()));
        this.txtStock.setText(String.valueOf(mProducto.getStock()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etqCUP = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        etqMarca = new javax.swing.JLabel();
        etqRubro = new javax.swing.JLabel();
        etqCapVol = new javax.swing.JLabel();
        txtCapVol = new javax.swing.JTextField();
        etqUnidad = new javax.swing.JLabel();
        etqPreUn = new javax.swing.JLabel();
        txtPrecUni = new javax.swing.JTextField();
        etqStock = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCerrar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtCUP = new javax.swing.JLabel();
        txtRubro = new javax.swing.JLabel();
        txtMarca = new javax.swing.JLabel();
        txtDesc = new javax.swing.JLabel();
        txtUnidad = new javax.swing.JLabel();
        txtStock = new javax.swing.JLabel();

        setTitle("Modificación de Producto");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        etqCUP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etqCUP.setText("CUP:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Descripción:");

        etqMarca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etqMarca.setText("Marca:");

        etqRubro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etqRubro.setText("Rubro:");

        etqCapVol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etqCapVol.setText("Capacidad/Volumen:");

        txtCapVol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        etqUnidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etqUnidad.setText("Unidad:");

        etqPreUn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etqPreUn.setText("Precio Unitario:");

        txtPrecUni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        etqStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etqStock.setText("Stock:");

        btnCerrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/Cancel.png"))); // NOI18N
        btnCerrar.setToolTipText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/Save.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtCUP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCUP.setText("");

        txtRubro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtRubro.setText("");

        txtMarca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMarca.setText("");

        txtDesc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDesc.setText("");

        txtUnidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUnidad.setText("");

        txtStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtStock.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etqPreUn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(etqMarca)
                                    .addComponent(etqCapVol))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtPrecUni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                            .addComponent(txtCapVol, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(etqUnidad)
                                            .addComponent(etqStock))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtUnidad)
                                            .addComponent(txtStock)))
                                    .addComponent(txtMarca)
                                    .addComponent(txtDesc)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etqCUP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCUP, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(etqRubro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtRubro)))
                        .addGap(0, 86, Short.MAX_VALUE))))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(18, 18, 18)
                .addComponent(btnCerrar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etqCUP)
                            .addComponent(etqRubro)
                            .addComponent(txtCUP)
                            .addComponent(txtRubro))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etqMarca)
                            .addComponent(txtMarca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDesc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etqCapVol)
                            .addComponent(txtCapVol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etqUnidad)
                            .addComponent(txtUnidad))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etqPreUn)
                            .addComponent(txtPrecUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etqStock)
                            .addComponent(txtStock))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean isEstado() {
        return estado;
    }

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        formWindowClosing(null);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (!this.txtUnidad.getText().equals("No posee") || this.txtCapVol.getText().equals("")) {
            this.txtCapVol.setText(this.txtCapVol.getText().replace(",", "."));
            if (Validacion.validacionFloat(this.txtCapVol.getText())) {
                this.mProducto.setCap_vol_long(Float.parseFloat(this.txtCapVol.getText()));
                if (!this.txtPrecUni.getText().equals("")) {
                    this.txtPrecUni.setText(this.txtPrecUni.getText().replace(",", "."));
                    if (Validacion.validacionFloat(txtPrecUni.getText())) {
                        this.mProducto.setPrecio_Unitario(Float.parseFloat(this.txtPrecUni.getText()));
                        if (CONTROLADOR_V.getContro_m().modificarProducto(mProducto)) {
                            CONTROLADOR_V.mensaje("El Producto fue Modificado satisfactoriamente");
                            JOptionPane.showMessageDialog(this, "El Producto fue Modificado satisfactoriamente", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                            CONTROLADOR_V.cerrarBuscarGestionProducto("modificarProducto");
                        } else {
                            JOptionPane.showMessageDialog(this, "No se pudo modificar el Producto.", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        this.txtPrecUni.requestFocus();
                        this.txtPrecUni.selectAll();
                        JOptionPane.showMessageDialog(null, "Por favor verifique los datos ingresados.\nEjs: 234.23, 23416",
                                "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Este campo no puede estar vacio.", "Error", JOptionPane.ERROR_MESSAGE);
                    this.txtPrecUni.requestFocus();
                    this.txtPrecUni.selectAll();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Por favor verifique el valos ingresado. La forma correcta es ej: 34.55", "Error", JOptionPane.ERROR_MESSAGE);
                this.txtCapVol.setBorder(new LineBorder(Color.red));
                this.txtCapVol.requestFocus();
                this.txtCapVol.selectAll();
            }
        } else {
            if (!this.txtPrecUni.getText().equals("")) {
                this.txtPrecUni.setText(this.txtPrecUni.getText().replace(",", "."));
                if (Validacion.validacionFloat(txtPrecUni.getText())) {
                    this.mProducto.setPrecio_Unitario(Float.parseFloat(this.txtPrecUni.getText()));
                    CONTROLADOR_V.getContro_m().modificarProducto(mProducto);
                    CONTROLADOR_V.mensaje("El Producto fue Modificado satisfactoriamente");
                    JOptionPane.showMessageDialog(this, "El Producto fue Modificado satisfactoriamente", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                    CONTROLADOR_V.cerrarBuscarGestionProducto("Modificar");
                } else {
                    this.txtPrecUni.requestFocus();
                    this.txtPrecUni.selectAll();
                    JOptionPane.showMessageDialog(null, "Por favor verifique los datos ingresados.\nEjs: 234.23, 23416",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Este campo no puede estar vacio.", "Error", JOptionPane.ERROR_MESSAGE);
                this.txtPrecUni.requestFocus();
                this.txtPrecUni.selectAll();
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int op = JOptionPane.showConfirmDialog(this, "¿Desea cerrar la ventana de Modificar?.\n"
                + "Perdera los datos cargados", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        if (op == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel etqCUP;
    private javax.swing.JLabel etqCapVol;
    private javax.swing.JLabel etqMarca;
    private javax.swing.JLabel etqPreUn;
    private javax.swing.JLabel etqRubro;
    private javax.swing.JLabel etqStock;
    private javax.swing.JLabel etqUnidad;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txtCUP;
    private javax.swing.JTextField txtCapVol;
    private javax.swing.JLabel txtDesc;
    private javax.swing.JLabel txtMarca;
    private javax.swing.JTextField txtPrecUni;
    private javax.swing.JLabel txtRubro;
    private javax.swing.JLabel txtStock;
    private javax.swing.JLabel txtUnidad;
    // End of variables declaration//GEN-END:variables
}