/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.interfaz;

import java.awt.Dimension;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import vista.CONTROLADOR_V;

/**
 *
 * @author vicente
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

        Dimension dim = super.getToolkit().getScreenSize();
        this.setSize(dim.width, dim.height - 30);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraSalida = new javax.swing.JToolBar();
        etqEstadoOperac = new javax.swing.JLabel();
        panelFondo = new JDesktopPane();
        barraBotones = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnAltaStock = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnGestProducto = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnGestRubro = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnGestMarca = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnGestProv = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnGestCliente = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestion de Negocio");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        barraSalida.setFloatable(false);
        barraSalida.setRollover(true);

        etqEstadoOperac.setText("");
        barraSalida.add(etqEstadoOperac);

        getContentPane().add(barraSalida, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(panelFondo, java.awt.BorderLayout.CENTER);

        barraBotones.setFloatable(false);
        barraBotones.setRollover(true);
        barraBotones.add(jSeparator1);

        btnAltaStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/add stock.png"))); // NOI18N
        btnAltaStock.setText("Alta Stock");
        btnAltaStock.setToolTipText("Alta Stock");
        btnAltaStock.setFocusable(false);
        btnAltaStock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAltaStock.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAltaStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaStockActionPerformed(evt);
            }
        });
        barraBotones.add(btnAltaStock);
        barraBotones.add(jSeparator2);

        btnGestProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/product.png"))); // NOI18N
        btnGestProducto.setText("Gestion de Producto");
        btnGestProducto.setToolTipText("Gestion de Producto");
        btnGestProducto.setFocusable(false);
        btnGestProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGestProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGestProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestProductoActionPerformed(evt);
            }
        });
        barraBotones.add(btnGestProducto);
        barraBotones.add(jSeparator3);

        btnGestRubro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/rubro 64x64.png"))); // NOI18N
        btnGestRubro.setText("Gestion de Rubro");
        btnGestRubro.setToolTipText("Gestion de Rubro");
        btnGestRubro.setFocusable(false);
        btnGestRubro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGestRubro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGestRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestRubroActionPerformed(evt);
            }
        });
        barraBotones.add(btnGestRubro);
        barraBotones.add(jSeparator4);

        btnGestMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/marca 64x64.png"))); // NOI18N
        btnGestMarca.setText("Gestion de Marca");
        btnGestMarca.setToolTipText("Gestion de Marca");
        btnGestMarca.setFocusable(false);
        btnGestMarca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGestMarca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGestMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestMarcaActionPerformed(evt);
            }
        });
        barraBotones.add(btnGestMarca);
        barraBotones.add(jSeparator5);

        btnGestProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/provider 64x64.png"))); // NOI18N
        btnGestProv.setText("Gestion de Proveedor");
        btnGestProv.setToolTipText("Gestion de Proveedor");
        btnGestProv.setFocusable(false);
        btnGestProv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGestProv.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGestProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestProvActionPerformed(evt);
            }
        });
        barraBotones.add(btnGestProv);
        barraBotones.add(jSeparator6);

        btnGestCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/people.png"))); // NOI18N
        btnGestCliente.setText("Gestion de Ciente");
        btnGestCliente.setToolTipText("Gestion de Ciente");
        btnGestCliente.setFocusable(false);
        btnGestCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGestCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGestCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestClienteActionPerformed(evt);
            }
        });
        barraBotones.add(btnGestCliente);
        barraBotones.add(jSeparator7);

        getContentPane().add(barraBotones, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaStockActionPerformed
        CONTROLADOR_V.iniciaAltaStock();
    }//GEN-LAST:event_btnAltaStockActionPerformed

    private void btnGestProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestProductoActionPerformed
        CONTROLADOR_V.iniciaSeleccionGestionProducto();
    }//GEN-LAST:event_btnGestProductoActionPerformed

    private void btnGestRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestRubroActionPerformed
        CONTROLADOR_V.iniciaSeleccionGestionRubro();
    }//GEN-LAST:event_btnGestRubroActionPerformed

    private void btnGestMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestMarcaActionPerformed
        CONTROLADOR_V.iniciaSeleccionGestionMarca();
    }//GEN-LAST:event_btnGestMarcaActionPerformed

    private void btnGestProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestProvActionPerformed
        CONTROLADOR_V.iniciaSeleccionGestionProveedor();
    }//GEN-LAST:event_btnGestProvActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int op = JOptionPane.showConfirmDialog(this, "¿Desea cerrar la aplicacion?.", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        if (op == JOptionPane.YES_OPTION) {            
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnGestClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestClienteActionPerformed
        CONTROLADOR_V.iniciaSeleccionGestionCliente();
    }//GEN-LAST:event_btnGestClienteActionPerformed
    public JDesktopPane getPanel() {
        return panelFondo;
    }

    /**
     * @param args the command line arguments
     */
    public void mensaje(String mensaje) {
        this.etqEstadoOperac.setText(mensaje);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraBotones;
    private javax.swing.JToolBar barraSalida;
    private javax.swing.JButton btnAltaStock;
    private javax.swing.JButton btnGestCliente;
    private javax.swing.JButton btnGestMarca;
    private javax.swing.JButton btnGestProducto;
    private javax.swing.JButton btnGestProv;
    private javax.swing.JButton btnGestRubro;
    private javax.swing.JLabel etqEstadoOperac;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JDesktopPane panelFondo;
    // End of variables declaration//GEN-END:variables
}
