/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.interfaz;

import vista.CONTROLADOR_V;

/**
 *
 * @author vicente-dell
 */
public class SeleccionGestionCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form SeleccionGestionCliente
     */
    public SeleccionGestionCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAltaCliente = new javax.swing.JButton();
        btnModifCliente = new javax.swing.JButton();
        btnElimCliente = new javax.swing.JButton();

        setTitle("Seleccionar la Gestion a Realizar");

        btnAltaCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAltaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/add people 64x64.png"))); // NOI18N
        btnAltaCliente.setText("Alta Cliente");
        btnAltaCliente.setToolTipText("Alta Cliente");
        btnAltaCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAltaCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAltaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaClienteActionPerformed(evt);
            }
        });

        btnModifCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnModifCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagen/update people 64x64.png"))); // NOI18N
        btnModifCliente.setText("Modificar Cliente");
        btnModifCliente.setToolTipText("Modificar Cliente");
        btnModifCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModifCliente.setVerifyInputWhenFocusTarget(false);
        btnModifCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModifCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifClienteActionPerformed(evt);
            }
        });

        btnElimCliente.setText("Eliminar Cliente");
        btnElimCliente.setToolTipText("Eliminar Cliente");
        btnElimCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAltaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModifCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnElimCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnElimCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModifCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(btnAltaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaClienteActionPerformed
        CONTROLADOR_V.iniciaAltaCliente();
    }//GEN-LAST:event_btnAltaClienteActionPerformed

    private void btnModifClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifClienteActionPerformed
        CONTROLADOR_V.iniciaBuscarGestion("clienteModificar");
    }//GEN-LAST:event_btnModifClienteActionPerformed

    private void btnElimClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimClienteActionPerformed
        CONTROLADOR_V.iniciaBuscarGestion("clienteEliminar");
    }//GEN-LAST:event_btnElimClienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltaCliente;
    private javax.swing.JButton btnElimCliente;
    private javax.swing.JButton btnModifCliente;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
